name: Scala CI

on: [push]

jobs:
  build:
    strategy:
      matrix: 
        scala: ["2.11.12", "2.12.8", "2.13.1"]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache Ivy
      uses: actions/cache@v1.0.0
      with:
        path: ~/.ivy2
        key: ${{ runner.os }}-ivy
    - name: Cache SBT
      uses: actions/cache@v1.0.0
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt
    - name: Cache Coursier
      uses: actions/cache@v1.0.0
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-coursier

    - name: Run tests
      run: sbt ++$SCALA_VERSION test
      env:
        SCALA_VERSION: ${{ matrix.scala }}

    - name: Publish
      run: sbt ++$SCALA_VERSION publish
      env:
        SCALA_VERSION: ${{ matrix.scala }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
